In [17]:
import imdb

In [18]:
import numpy as np

In [19]:
%time train = imdb.IMDBdata("aclImdb_small/train")

CPU times: user 17.8 s, sys: 579 ms, total: 18.4 s
Wall time: 19.1 s


In [20]:
w = np.random.random(train.X.shape[1])
print(w)

[ 0.86802719  0.21627044  0.0233051  ...,  0.0208194   0.08739342
  0.54437077]


In [22]:
train.X.shape

(7222, 58162)

In [23]:
%%time
train.X[0,:].dot(w)

CPU times: user 292 µs, sys: 64 µs, total: 356 µs
Wall time: 330 µs


array([ 211.38409129])

In [24]:
%%time
sum = 0
for i in range(train.X.shape[1]):
    sum += train.X[0,i] * w[i]
print(sum)

211.384091293
CPU times: user 1.5 s, sys: 13.4 ms, total: 1.51 s
Wall time: 1.51 s


In [25]:
train.Y

array([-1.,  1.,  1., ...,  1., -1.,  1.])

In [26]:
word_counts = np.array(train.X[train.Y == -1,:].sum(axis=0)).flatten()
word_counts

array([  83,  493, 6948, ...,    1,    1,    1], dtype=int64)

In [27]:
sorted_words = list(reversed(np.argsort(word_counts)))
sorted_words[0:10]

[40, 50, 75, 23, 82, 33, 14, 234, 231, 233]

In [28]:
sorted_words[0]

40

In [29]:
train.vocab.GetWord(sorted_words[0])

'the'

In [30]:
[train.vocab.GetWord(sorted_words[x]) for x in range(10)]

['the', ',', '.', 'a', 'and', 'to', 'of', '>', '<', '/']

In [31]:
x = range(10)

In [32]:
list(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
[a + 1 for a in x]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]